name: nixpkgs-update
version: 0.2.0
synopsis: Tool for semi-automatic updating of nixpkgs repository
description: nixpkgs-update provides tools for updating of nixpkgs
  packages in a semi-automatic way. Mainly, it is used to run the GitHub
  bot @r-ryantm, but the underlying update mechanisms should be
  generally useful and in a later version should be exposed as a
  command-line tool.
license: CC0-1.0
author: Ryan Mulligan et al.
maintainer: ryan@ryantm.com
copyright: 2018-2020 Ryan Mulligan et al.
category: Web
extra-source-files:
- README.md

github: ryantm/nixpkgs-update

ghc-options: -Wall -O2 -flate-specialise -fspecialise-aggressively -fplugin=Polysemy.Plugin

default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - conduit
  - containers
  - cryptohash-sha256
  - directory >= 1.3 && < 1.4
  - errors
  - filepath
  - github
  - hex
  - http-client-tls
  - http-conduit
  - iso8601-time
  - lifted-base
  - mtl
  - neat-interpolation >= 0.3 && < 0.4
  - optparse-applicative
  - parsec
  - parsers
  - partial-order
  - polysemy
  - polysemy-plugin
  - regex-applicative-text
  - servant
  - servant-client
  - sqlite-simple
  - template-haskell
  - temporary
  - text
  - time >= 1.8 && < 1.10
  - transformers
  - typed-process
  - unix
  - unordered-containers
  - vector
  - versions
  - xdg-basedir
  - zlib

executables:
  nixpkgs-update:
    source-dirs: src
    main: Main.hs

tests:
  doctests:
    main: doctests.hs
    ghc-options: -threaded
    source-dirs: test
    dependencies:
      - doctest
  spec:
    main: NixPkgsUpdateSpec.hs
    ghc-options: -threaded
    source-dirs: test
    dependencies:
      - hspec
